# Generated by Django 3.0.4 on 2020-06-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manytomany',
            name='m2m',
            field=models.ManyToManyField(blank=True, to='app.M2MDependency'),
        ),
    ]
