# Generated by Django 3.0.2 on 2020-02-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('date', models.DateField()),
                ('age', models.PositiveSmallIntegerField()),
                ('sex', models.BooleanField()),
                ('gender', models.NullBooleanField()),
            ],
        ),
    ]
