language: python
python:
  - '3.6'
install:
  - curl -L https://tarantool.io/installer.sh | sudo bash
  - pip install -r requirements.txt
  - pip install git+https://github.com/artembo/tarantool-python@dbapi2
script:
  - cd django_app && python3 manage.py test
deploy:
  provider: pypi
  username: __token__
  password:
    secure: Xog6HoSUDA80WIcAWPf3Bm7FT0tmU/g475ald4BsFCSAnJKGnIts+3R2PifumDtcWjS4G+Okd5PkgHF0kf6ApWzARYjWJY6FoYIrQy4mMwpjgwr72htNHS8/Oy1vRHgMhIs68nIms5JvHfbgnrSTCyWBAPKZtRI/dihsH69AVBL/FxpeyzGG9txjbooEA1Mw96VEwvWmoX4YqgNvx8JyA7REyIEnEBvXCJ7TjCKzfpzj7nEimZe0l5h5EgMeqLeiHT4NI6Iq50smSgXl7VmMlEh5AM9esM3iqIHALaq13xWUUZ8zkxfn+lnP9jHdf+MH03R//MOfyO6lNI5t9mw1ASvPE3EA6FMGSDehLfIOV/cc/fu/JojDrrmLifYzZUHAhGEVQ6KWKoI0n9dhfipiy3ym9NvnDn6pATDp6NdH9AWsgFalEhEAMHDomR8u5cJxCX632RVXalwg+U3P3b0hG3N0DMTzPXYQXQO5eZNT4qFEu+0xHQceGaOdSWjawTMM30IOFzA+0sg8sFUpx8LAEdOlx/GrOWW7gTP4l+FXXOa1WGHXVXgQ3r5Iud/Hkfbh8dFPzeRg2UkgRX7VRTmDW7AOgSDSD143MGqeGzYNDeYsNj6XtCOUR8OsHfBKePxVJwPVoiyLThU68+Tm9GRgpCG0K94EPZbooZqPJfZQjqo=
  on:
    tags: true
  skip_cleanup: true
