language: python
python:
  - '3.6'
install:
  - curl -L https://tarantool.io/installer.sh | sudo bash
  - pip install -r requirements.txt
  - pip install git+https://github.com/artembo/tarantool-python@dbapi2
script:
  - cd django_app && python3 manage.py test

deploy:
  provider: pypi
  username: __token__
  password:
    secure: WTVKuKirE7pijGteNBbauyZ+uz7XKn7fFNR02UTXot23DoWd0dMxO6az/VMFGLdpegOzoAuePdtv+OZqtC9++1Bbg7KJ2CT1yiE9j2NKrDvvWaC0N6kOdIrmljHy0mlYkc95S/g/CI/5/FvLA2YOym/fy/N3B5T6Awu4qD7ZlaR22iTufH+leSq/0D1zks1ZKhBnxOnl3KxAJKlBqSHAbzh44wo3WlUzHWabtM/kgNRL2/9qMS6Laslrnjcb8ubpTK2/9gpPiseQvdydspTkZRbOspN4fXUHEEyMPb/jAHK6U/Z0hFf3aWi4xdLW6sj3sdYEtgV8Ld59INaUzNP0Ip9uyo9+Ic1zvJqhcgjhBwuLhPr+BYX8iYddFAZUgfoQ70g3I5GiUQKx6+wU/If/fxfmzOOTH9/ow1uEI/8j6NtKd/3nGpOEIoTmwTTxwE/OCTyBKsEzOF9fK2x2Tw3zpZmj4bRIKEtPccikejYStVlhaTQRn8fmaCpNnnUD/W8csf+fp83J8O4tlgLqnT0+RN4+6dl7+iknrz6pf/MqoDvcc8gPwnZtGGhxf6Hxf+jzYErP0Ywm49Lp7vyHBRAFJBpzKihPkoZXImDoUBM5ZYWy35tnqCZN3CsmJuzZuoAEgUQS8ZioGIgKQPbsMM0g8a9gl969o2nWDfjcD4uSqko=
  on:
    tags: true
  skip_cleanup: true
