language: python
python:
  - '3.6'
install:
  - curl -L https://tarantool.io/installer.sh | sudo bash
  - pip install -r requirements.txt
  - pip install git+https://github.com/artembo/tarantool-python@dbapi2
script:
  - cd django_app && python3 manage.py test && cd ..
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: "EWmmZCZcCCtMvlvEQNZkk3aBOPDa2AdJcklMnCHDfzXX3YOhnJQOpTYCTAdDIIDx/pvx9SIo6sDyoHhydbGh2a8D1dyIudW1dwBqKIJLcBU3fJ+/BkjUadw4eqToIiqP1jyZ2LEKillLmgtetkewkyPwXKhZTMK9mkQtWzZ6T6nbN20SlXAF+/7h1+cuFFiKuV+EsriJUIGINHEwUG4l6h2l32wlPKwQ+nOIVldJLjGznOdQ7yBLf1iup2pQ6dyk/CwovW+apAxgLOPpf7CkFUzTxpM5WjL+bUdsVi5eOIKnOwSHYow5PyGNa2X8Q/x31UL/YB9Vyu+UQYLjlsOIj4GYJeOGugn3ei6HrLtCNroPB3QVWbLO3VRhb9u+gxFFcqZT2x9jF0Lun8UcAllPxeHpDjG6rcf2U8uIKsRuWOr3F8AwH6k3Nv3BNKATodOnAQFj0VOZAJrRRg7lx328Ez4tPQyZJjUEJwRBTg9irL7mqRhewHQzhZ5nuw9PFY+s5jkcu/2p8s2VfleDI3b/lbLuNWYaJQcwTfYm+XoyZupPj9ayjiTuI8yTE7yczoI/k4kcxewq8na5f5CKXXph0NrY+4/BJbZlWP2HvsDrF5MeIU90xuDMgH01CUaU7LXmj/8fSL0/WHhMLECRYqGJzvPBFJcyli8k9RyjvdikJEY="
  on:
    tags: true
  skip_cleanup: true
